### ISSUE TITLE
Working together?

### ISSUE THREAD

**Issue by AchimTuran** [LiveAsynchronousVisualizedArchitecture/lava#17]
Hi,
I'm currently working on a really similar project like lava but specific for audio. Are you interested in working together. If so please contact me via email.

**Comment by LiveAsynchronousVisualizedArchitecture** [comment]
Hi Achim, I just saw your message on my github page for LAVA and would love to work together. I'll look through your page a bit and you can let me know any suggestions you have.  If you like, I can go through my plans as well as the overall architecture in more detail. I'll try to contact you through email as well.

**Comment by AchimTuran** [comment]
Hi,
awesome! Yes let us discuss further details via email, Github issues is not a convenient way.
Sorry to project is currently not hosted on Github, but you will find a lot of code for related add-on development. To be honest this is a different topic.
Looking forward to your email.
